BB_CONF_FRAGMENT_SUMMARY = "Accept NXP licenses"
BB_CONF_FRAGMENT_DESCRIPTION = "Accept all NXP licenses needed to build any reciped added or used by the meta-kiss-nxp layer."

LICENSE_FLAGS_ACCEPTED += "NXP_EULA_v57 NXP_EULA_v58"
